/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
 *  Classname  employeapp.java
 * @reference employee app arraylist GUI FH
 * @author fsheridan
 *
 */

package taba;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author connd
 */
public class productGUI extends javax.swing.JFrame {
    private ArrayList <products> products;
    private products ranselect;
    /**
     * Creates new form productGUI
     */
    public productGUI() {
        products = new ArrayList<>();
        initComponents();
        NameJL.setVisible(false);
        numberfield.setVisible(false);
        namefield.setVisible(false);
        numberJL.setVisible(false);
        priceJL.setVisible(false);
        pricefield.setVisible(false);
        descriptionJL.setVisible(false);
        descriptionfield.setVisible(false);
        urlJL.setVisible(false);
        urlfield.setVisible(false);
        publisherJL.setVisible(false);
        publisherfield.setVisible(false);
        colourJL.setVisible(false);
        colourfield.setVisible(false);
        brandJL.setVisible(false);
        brandfield.setVisible(false);
        typeJL.setVisible(false);
        typefield.setVisible(false);
        sizeJL.setVisible(false);
        sizefield.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        tittleJL = new javax.swing.JLabel();
        boardgameRB = new javax.swing.JRadioButton();
        clothingRB = new javax.swing.JRadioButton();
        craftsuppliesRB = new javax.swing.JRadioButton();
        NameJL = new javax.swing.JLabel();
        numberJL = new javax.swing.JLabel();
        descriptionJL = new javax.swing.JLabel();
        priceJL = new javax.swing.JLabel();
        urlJL = new javax.swing.JLabel();
        publisherJL = new javax.swing.JLabel();
        typeJL = new javax.swing.JLabel();
        sizeJL = new javax.swing.JLabel();
        colourJL = new javax.swing.JLabel();
        brandJL = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        numberfield = new javax.swing.JTextField();
        descriptionfield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();
        urlfield = new javax.swing.JTextField();
        publisherfield = new javax.swing.JTextField();
        typefield = new javax.swing.JTextField();
        sizefield = new javax.swing.JTextField();
        colourfield = new javax.swing.JTextField();
        brandfield = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        displaybtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        loadbtn = new javax.swing.JButton();
        randombtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tittleJL.setText("product c.r.u.d system");

        buttonGroup.add(boardgameRB);
        boardgameRB.setText("board game");
        boardgameRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardgameRBActionPerformed(evt);
            }
        });

        buttonGroup.add(clothingRB);
        clothingRB.setText("clothing");
        clothingRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothingRBActionPerformed(evt);
            }
        });

        buttonGroup.add(craftsuppliesRB);
        craftsuppliesRB.setText("craft supplies");
        craftsuppliesRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                craftsuppliesRBActionPerformed(evt);
            }
        });

        NameJL.setText("name");

        numberJL.setText("number");

        descriptionJL.setText("description");

        priceJL.setText("price");

        urlJL.setText("url");

        publisherJL.setText("publisher");

        typeJL.setText("type");

        sizeJL.setText("size");

        colourJL.setText("colour");

        brandJL.setText("brand");

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });

        addbtn.setText("add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        displaybtn.setText("display");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });

        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        searchbtn.setText("search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        loadbtn.setText("load");
        loadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbtnActionPerformed(evt);
            }
        });

        randombtn.setText("random");
        randombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randombtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(tittleJL, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameJL, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberJL)
                    .addComponent(descriptionJL)
                    .addComponent(priceJL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandJL)
                    .addComponent(colourJL)
                    .addComponent(sizeJL)
                    .addComponent(typeJL)
                    .addComponent(publisherJL)
                    .addComponent(urlJL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchbtn)
                            .addComponent(addbtn))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loadbtn)
                            .addComponent(displaybtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(savebtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(randombtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urlfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typefield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizefield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colourfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(craftsuppliesRB)
                    .addComponent(boardgameRB)
                    .addComponent(clothingRB))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tittleJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boardgameRB)
                    .addComponent(NameJL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clothingRB)
                    .addComponent(numberJL)
                    .addComponent(numberfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(craftsuppliesRB)
                    .addComponent(descriptionJL)
                    .addComponent(descriptionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceJL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlJL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publisherJL)
                    .addComponent(publisherfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeJL)
                    .addComponent(typefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeJL)
                    .addComponent(sizefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colourJL)
                    .addComponent(colourfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandJL)
                    .addComponent(brandfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displaybtn)
                    .addComponent(savebtn)
                    .addComponent(addbtn))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbtn)
                    .addComponent(loadbtn)
                    .addComponent(randombtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boardgameRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardgameRBActionPerformed
        // TODO add your handling code here:
           NameJL.setVisible(true);
           namefield.setVisible(true);
        numberJL.setVisible(true);
        numberfield.setVisible(true);
        priceJL.setVisible(true);
        pricefield.setVisible(true);
        descriptionJL.setVisible(true);
        descriptionfield.setVisible(true);
        urlJL.setVisible(true);
        urlfield.setVisible(true);
        publisherJL.setVisible(true);
        publisherfield.setVisible(true);
        colourJL.setVisible(false);
        colourfield.setVisible(false);
        brandJL.setVisible(false);
        brandfield.setVisible(false);
        typeJL.setVisible(false);
        typefield.setVisible(false);
        sizeJL.setVisible(false);
        sizefield.setVisible(false);
    }//GEN-LAST:event_boardgameRBActionPerformed

    private void craftsuppliesRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_craftsuppliesRBActionPerformed
        // TODO add your handling code here:
           NameJL.setVisible(false);
        namefield.setVisible(false);
        numberfield.setVisible(true);
        numberJL.setVisible(true);
        priceJL.setVisible(true);
        pricefield.setVisible(true);
        descriptionJL.setVisible(true);
        descriptionfield.setVisible(true);
        urlJL.setVisible(true);
        urlfield.setVisible(true);
        publisherJL.setVisible(false);
        publisherfield.setVisible(false);
        colourJL.setVisible(true);
        colourfield.setVisible(true);
        brandJL.setVisible(true);
        brandfield.setVisible(true);
        typeJL.setVisible(true);
        typefield.setVisible(true);
        sizeJL.setVisible(false);
        sizefield.setVisible(false);
    }//GEN-LAST:event_craftsuppliesRBActionPerformed

    private void clothingRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothingRBActionPerformed
        // TODO add your handling code here:
           NameJL.setVisible(false);
        namefield.setVisible(false);
       numberJL.setVisible(true);
        numberfield.setVisible(true);
        priceJL.setVisible(true);
        pricefield.setVisible(true);
        descriptionJL.setVisible(true);
        descriptionfield.setVisible(true);
        urlJL.setVisible(true);
        urlfield.setVisible(true);
        publisherJL.setVisible(false);
        publisherfield.setVisible(false);
        colourJL.setVisible(true);
        colourfield.setVisible(true);
        brandJL.setVisible(false);
        brandfield.setVisible(false);
        typeJL.setVisible(true);
        typefield.setVisible(true);
        sizeJL.setVisible(true);
        sizefield.setVisible(true);
    }//GEN-LAST:event_clothingRBActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
         if(boardgameRB.isSelected()){
            boardgame b = new boardgame();
            b.setNumber(numberfield.getText());
            b.setDescription(descriptionfield.getText());
            b.setPrice(pricefield.getText());
            b.setUrl(urlfield.getText());
            b.setName(namefield.getText());
            b.setPublisher(publisherfield.getText());
            products.add(b);
        }
        else if(clothingRB.isSelected()){
            clothing c = new clothing();
            c.setNumber(numberfield.getText());
            c.setDescription(descriptionfield.getText());
            c.setPrice(pricefield.getText());
            c.setUrl(urlfield.getText());
            c.settype(typefield.getText());
            c.setsize(sizefield.getText());
            c.setcolour(colourfield.getText());
            products.add(c);
        }
        else if (craftsuppliesRB.isSelected()){
            craftSupplies cs = new craftSupplies();
            cs.setNumber(numberfield.getText());
            cs.setDescription(descriptionfield.getText());
            cs.setPrice(pricefield.getText());
            cs.setUrl(urlfield.getText());
            cs.settype(typefield.getText());
            cs.setbrand(brandfield.getText());
            cs.setcolour(colourfield.getText());
            products.add(cs);
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
        // TODO add your handling code here:
         for (int i = 0; i < products.size(); i++) {
            products p = products.get(i);
            JOptionPane.showMessageDialog(null, p.getDetails());
         }
    }//GEN-LAST:event_displaybtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here: 
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            f = new File("output.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(products);
            oStream.close();
        }
        catch(IOException p){
            System.out.println(p);
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        if (products.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no products to search");
        } 
        else {
            String searchTerm = JOptionPane.showInputDialog(null, "Enter an number to search for.");
           
            for(products p:products){
                if(p.getNumber().equals(searchTerm)){
                    JOptionPane.showMessageDialog(null,p.getDetails());
                }
            }
        }

    }//GEN-LAST:event_searchbtnActionPerformed

    private void loadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            f = new File("output.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            
            products = (ArrayList<products>)oStream.readObject();
            oStream.close();
        }
        catch(IOException | ClassNotFoundException p){
            System.out.println(p);
        }
    }//GEN-LAST:event_loadbtnActionPerformed

    private void randombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randombtnActionPerformed
        // TODO add your handling code here:
    if(randombtn.getActionCommand().equals("")) {
             Random rand_gen = new Random();
             int index_selected = rand_gen.nextInt(products.size());
            ranselect = products.remove(index_selected);
             JOptionPane.showMessageDialog(null, ranselect.getDetails());   
             /**
     * @refrence https://stackoverflow.com/questions/56054363/how-do-i-randomly-perform-buttons-action
     */
    }

    }//GEN-LAST:event_randombtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameJL;
    private javax.swing.JButton addbtn;
    private javax.swing.JRadioButton boardgameRB;
    private javax.swing.JLabel brandJL;
    private javax.swing.JTextField brandfield;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton clothingRB;
    private javax.swing.JLabel colourJL;
    private javax.swing.JTextField colourfield;
    private javax.swing.JRadioButton craftsuppliesRB;
    private javax.swing.JLabel descriptionJL;
    private javax.swing.JTextField descriptionfield;
    private javax.swing.JButton displaybtn;
    private javax.swing.JButton loadbtn;
    private javax.swing.JTextField namefield;
    private javax.swing.JLabel numberJL;
    private javax.swing.JTextField numberfield;
    private javax.swing.JLabel priceJL;
    private javax.swing.JTextField pricefield;
    private javax.swing.JLabel publisherJL;
    private javax.swing.JTextField publisherfield;
    private javax.swing.JButton randombtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLabel sizeJL;
    private javax.swing.JTextField sizefield;
    private javax.swing.JLabel tittleJL;
    private javax.swing.JLabel typeJL;
    private javax.swing.JTextField typefield;
    private javax.swing.JLabel urlJL;
    private javax.swing.JTextField urlfield;
    // End of variables declaration//GEN-END:variables
}
